version: '3.9'
volumes:
  mongodb_data:
    driver: local
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: shaima
      MONGO_INITDB_ROOT_USERNAME: m0ng0db
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db